-- AlterTable
ALTER TABLE `cursante` ADD COLUMN `documentacion` ENUM('VERIFICADA', 'PENDIENTE') NOT NULL DEFAULT 'PENDIENTE',
    ADD COLUMN `estado` ENUM('ACTIVO', 'ADEUDANDO', 'BAJA') NOT NULL DEFAULT 'ACTIVO',
    ADD COLUMN `observaciones` TEXT NULL;
