INSERT INTO Instituto (nombre, distritoId)
SELECT v.nombre, v.distritoId
FROM (
    SELECT 'ISFD N°17' AS nombre, 21 AS distritoId
    UNION ALL SELECT 'ISFDyT N°49', 22
    UNION ALL SELECT 'ISFD N°1', 27
    UNION ALL SELECT 'ISFDyT N°103', 28
    UNION ALL SELECT 'ISFDyT N°46', 30
    UNION ALL SELECT 'ISFDyT N°105', 30
    UNION ALL SELECT 'ISFD N°106', 30
    UNION ALL SELECT 'ISFDyT N°83', 32
    UNION ALL SELECT 'ISFD N°41', 34
    UNION ALL SELECT 'ISFDyT N°53', 34
    UNION ALL SELECT 'ISFD N°39', 42
    UNION ALL SELECT 'ISFD N°34', 44
    UNION ALL SELECT 'ISFD N°29', 46
    UNION ALL SELECT 'ISFDyT N°42', 50
    UNION ALL SELECT 'ISFD N°110', 49
    UNION ALL SELECT 'ISFD N°141', 56
    UNION ALL SELECT 'ISFDyT N°15', 62
    UNION ALL SELECT 'ISFD N°119', 148
    UNION ALL SELECT 'ISFDyT N°126', 152
    UNION ALL SELECT 'ISFD N°129', 67
    UNION ALL SELECT 'ISFDyT N°20', 67
    UNION ALL SELECT 'ISFDyT N°13', 80
    UNION ALL SELECT 'ISFDyT N°40', 114
    UNION ALL SELECT 'ISFDyT N°57', 82
    UNION ALL SELECT 'ISFD N°19', 89
    UNION ALL SELECT 'ISFDyT N°63', 90
    UNION ALL SELECT 'ISFDyT N°81', 91
    UNION ALL SELECT 'ISFDyT N°10', 92
    UNION ALL SELECT 'ISFDyT N°166', 92
    UNION ALL SELECT 'ISFDyT N°33', 135
    UNION ALL SELECT 'ISFD N°3', 97
    UNION ALL SELECT 'ISFDyT N°25', 98
    UNION ALL SELECT 'ISFDyT N°48', 138
    UNION ALL SELECT 'ISFD N°16', 102
    UNION ALL SELECT 'ISFDyT N°27', 108
    UNION ALL SELECT 'ISFD N°22', 109
) AS v
LEFT JOIN Instituto i
    ON i.nombre = v.nombre
   AND i.distritoId = v.distritoId
WHERE i.id IS NULL;
